# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

social:
  twitter: "https://twitter.com/yourprofile"
  facebook: "https://facebook.com/yourprofile"
  email: "mailto:your.email@example.com"
  linkedin: "https://linkedin.com/in/yourprofile"
  whatsapp: "https://wa.me/yourphonenumber"

# SEO
marketing:
  seo:
    site_type: Project
    local_business_type: 'Software Consutling'
    org_name: 'Steven Zgaljic'
    description: 'A framework for building better software with a clear, adaptable approach for success.'
    twitter: ''
  analytics:
    google_analytics: 'G-CP0FEM9P19'
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "The F6 Framework"
      # Logo filename in `assets/media/` folder
      # filename: "logo.svg"
    button:
      enable: true
      text: "Get Involved"
      url: "about/"
    # show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: 'Â© {year} The F6 Framework. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/szgaljic/f6/'
    content_dir: 'starters/documentation/content'
    branch: 'main'
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/<USERNAME>/<REPO>/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/<USERNAME>/<REPO>/issues/new).'
  comment:
    provider: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
